/**
 * Dust policy for the local `undeployed` devnet — pure and dependency-free, so
 * it can be unit-tested without loading testkit or touching a node.
 *
 * "Dust" is what pays tx fees; it is generated by the NIGHT a wallet holds. On
 * the local devnet a wallet must be built with fee headroom or it cannot balance
 * its first tx, and a wallet holding zero NIGHT can never pay at all.
 */

/**
 * Fee headroom the local `undeployed` devnet needs to balance a tx. testkit's
 * `MidnightWalletProvider.build()` hard-codes `additionalFeeOverhead: 0n`
 * (`DEFAULT_DUST_OPTIONS`), which leaves a signer wallet unable to pay for its
 * first tx — the balancer retries for ~1h and then WASM-traps. This mirrors the
 * value PR #632's `OwnWalletProvider` uses for `undeployed`.
 */
export const UNDEPLOYED_FEE_OVERHEAD = 500_000_000_000_000_000n; // 5e17

/**
 * Minimum NIGHT a pooled wallet must report before it is usable. NIGHT generates
 * the dust that pays fees; a zero-NIGHT seed can never pay, so we reject it up
 * front rather than hang on its first tx.
 */
export const MIN_WALLET_NIGHT = 1n;

/**
 * A pooled wallet failed the funds gate — it holds no spendable NIGHT, so it can
 * never pay tx fees on the local devnet. Thrown at build time (fast) instead of
 * letting the wallet hang on its first unpayable tx.
 */
export class DustFundingError extends Error {
  constructor(
    readonly alias: string,
    readonly nightBalance: bigint,
  ) {
    super(
      `live wallet '${alias}' has no spendable dust (NIGHT balance ${nightBalance}). ` +
        `On the local 'undeployed' devnet this seed cannot pay tx fees — check that ` +
        'midnight-node --preset=dev funds its seed, or rotate the pool to a funded one.',
    );
    this.name = 'DustFundingError';
  }
}

/** Throw {@link DustFundingError} unless `nightBalance` clears {@link MIN_WALLET_NIGHT}. */
export function assertFunded(alias: string, nightBalance: bigint): void {
  if (nightBalance < MIN_WALLET_NIGHT) {
    throw new DustFundingError(alias, nightBalance);
  }
}
